name: bspoke_jitsi_web_plugin
description: A common plugin for the custom jitsi-meet web and mobile implementation for Virtual Hospital.
version: 0.0.3
homepage: https://bspokeinfotech.com/
repository: https://github.com/tanvir23/jitsi_meet

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"
  
dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.3
  meta: ^1.3.0
  flutter_web_plugins:
    sdk: flutter
  bspoke_jitsi_platform_interface: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      web:
        pluginClass: JitsiMeetPlugin
        fileName: jitsi_meet_web.dart
