name: bspoke_jitsi_platform_interface
description: A common platform interface for the jitsi meet plugin.
version: 0.0.2
homepage: https://bspokeinfotech.com/
repository: https://github.com/tanvir23/jitsi_meet

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

